#!/bin/sh
#
#	03-mysql/install - Install php-mysql files to $Top
#
if [ -d $Top/usr/lib ]; then
    find $Top/usr/lib -name '*.so' | xargs strip -v >>$Logs/striped_$Pkg.out
    find $Top/usr/lib -name '*.so' | xargs chmod -x
else
    echo "\aERROR: no $Top/usr/lib directory. Package will be empty."
fi
