FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV LANG=C
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -al'\necho \"Use: $TESTS_TOP/tests\\nto start the tests\"" >>/root/.bashrc

# Update/upgrade
RUN apt-get update
RUN apt-get upgrade -y

# Tools and tests deps
RUN apt-get install -y --no-install-recommends $TESTS_REQ

RUN mkdir -p $TESTS_TOP/dist
COPY php/info.php /var/www/html
COPY php/tests $TESTS_TOP
COPY php/run $TESTS_TOP
$TSTCOPY

CMD $TESTS_TOP/run
