FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV DEBVER $DEBVER
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -al'" >>/root/.bashrc

# Update/upgrade
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends apache2 vim

RUN mkdir -p $TESTS_TOP/dist
COPY php/tst $TESTS_TOP
COPY run $TESTS_TOP
$EXTCOPY

CMD $TESTS_TOP/run $PHPVER
