FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV CLI_DEPS $CLI_DEPS
ENV BUILD_NUM=$BUILD_NUM
ENV DEBVER=$DEBVER
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -al'\necho \"Use: $BUILD_TOP/build $PHPVER\\nto start the build\"" >>/root/.bashrc
RUN $ADDUSER

# Update/upgrade
RUN apt-get update
RUN apt-get upgrade -y

# Tools and build deps
RUN apt-get install -y --no-install-recommends $BUILD_REQ

RUN mkdir -p $BUILD_TOP/dist $BUILD_TOP/files
COPY $PHPSRC $BUILD_TOP/files
COPY pkgs $BUILD_TOP/pkgs
COPY php/build $BUILD_TOP
COPY php/run $BUILD_TOP
$BLDCOPY

CMD $BUILD_TOP/run $PHPVER
