#!/bin/sh
#
#	Test the use of multiple PHP versions
#
#	Usage:	[multi|.]/bake <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]
#
Prg=multi/`basename $0`
Dir=`dirname $0`
IniPwd=$PWD
TopDir=../
DebTop=${TopDir}debian
PhpTop=${TopDir}php
TlsTop=${TopDir}tools
MulTop=

Path() { realpath --relative-to=$IniPwd $1; }
test "$Dir" || Dir=`dirname \`realpath $0\``
expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
test "$Dir" = '.' || cd "$Dir"
#   Script's CWD is where it is located, but all messages assume PWD is top-level
test -d $DebTop || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
test -d $PhpTop || { echo "$Prg: missing 'php' directory." >&2;  exit 1; }
test -d $TlsTop || { echo "$Prg: missing 'tools' directory." >&2;  exit 1; }

DefDeb=`ls $DebTop | sort -n | tail -1`	# Default = latest
Base='epi-php'
Arch='amd64'
LF='
'
#
#    Parse args
#
for arg in "$@"
do
    d=`expr "$arg" : '\([5-9]\.[0-9]\.[0-9]\{,2\}-[0-9]\{,2\}*\)$'`
    v=`expr "$arg" : '\([0-9]\{1,\}\)$'`
    if [ "$d" ]; then
	ds="$ds $d"
    elif [ "$v" ]; then
	vs="$vs $v"
    else
	echo "$Prg: invalid PHP-dist-dir or Debian-version \"$arg\"" >&2
	exit 1
    fi
done

#
#   Check Debian version
#
re="`cat ${MulTop}mkre`"
for v in $vs
do
    if echo $v | egrep "^($re)$" >/dev/null && [ -f $DebTop/$v/name ]; then
	test "$DebNum" && echo "$Prg: discarding previously given Debian-version $DebNum (`cat $DebTop/$DebNum/name`)" >&2
	DebNum="$v"
    else
	echo "$Prg: unsupported Debian version \"$v\"" >&2
	echo "Supported Debian versions (default $DefDeb):" >&2
	ls $DebTop | sort -n | egrep "^($re)$" | while read v; do test -f $DebTop/$v/name && printf "    %2d (`cat $DebTop/$v/name`)\n" $v; done >&2
	exit 1
    fi
done
test "$DebNum" || DebNum=$DefDeb
DebVer="`cat $DebTop/$DebNum/name`"
DebDir=$DebTop/$DebNum

if [ -f $DebDir/Dockervars.sh ]; then
    eval `sed -n 's/^TESTS_REQ=/MULTI_REQ=/p' $DebDir/Dockervars.sh`
    MULTI_REQ="$MULTI_REQ `sed -nr 's/LIBZIP="([^"]+)"/\1/p' $DebDir/Dockervars.sh`"
else
    echo "$Prg: missing debian/$DebNum/Dockervars.sh" >&2
    exit 1
fi
DistDir=$DebDir/dist
MultDir=$DebDir/multi
Logs=$MultDir/logs
Pkgs=$MultDir/pkgs

#
#   Check PHP-dists
#
DistOK()
{
    # global Base Arch
    local path dist
    path="$1"
    test -d "$path" || return 1
    dist=`basename $path`
    test -s $path/$Base-$2.$3-cli_${dist}_$Arch.deb || return 1
    test -s $path/$Base-$2.$3-fpm_${dist}_$Arch.deb || return 1
    return 0
}

nd=0
test -d $Pkgs && rm -f $Pkgs/*.deb
if [ "$ds" ]; then
    for d in $ds
    do
	eval `echo "$d" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})-([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
	if DistOK $DistDir/$d $Maj $Min; then
	    mkdir -p $Pkgs
	    ln $DistDir/$d/$Base-$Maj.$Min-cli_${d}_$Arch.deb $Pkgs
	    ln $DistDir/$d/$Base-$Maj.$Min-fpm_${d}_$Arch.deb $Pkgs
	    test -s $DistDir/$d/$Base-$Maj.$Min-mysql_${d}_$Arch.deb && ln $DistDir/$d/$Base-$Maj.$Min-mysql_${d}_$Arch.deb $Pkgs
	    test "$HOSTFMT" && h=`echo "$HOSTFMT" | awk -F. '{print $1}' | sed -e "s/%M/$Maj/" -e "s/%m/$Min/"` || h=php$Maj$Min
	    w=$MultDir/www/$h
	    test -d $w || mkdir -p $w
	    test -f $w/index.php || echo "<?php header('Location: info.php'); ?>" >$w/index.php
	    cp -p $PhpTop/run/info.php $w
	    cp -p ${MulTop}run/run $MultDir
	    nd=`expr $nd + 1`
	else
	    echo "$Prg: debian/$DebNum/dist/$d does not contain the necessary $Base cli and fpm packages" >&2
	    exit 1
	fi
    done
fi
if [ $nd -eq 0 ]; then
    echo "Usage: $Prg <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]" >&2
    Sep=''
    for dir in $DistDir/[5-9].[0-9].[0-9]*-[0-9]*
    do
	eval `basename $dir | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})-([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
	if DistOK $dir $Maj $Min; then
	    Dists="$Dists$Sep`basename $dir`"
	    Sep="$LF"
	fi
    done
    if [ "$Dists" ]; then
	echo "Available dists for Debian version $DebNum ($DebVer):" >&2
	echo "$Dists" | sed 's/^/    /' >&2
    fi
    exit 1
fi

#
#   Build container
#
MULTI_TOP=/opt/multi
MULTI_BASE=epi-multi-php
MULTI_IMG=$MULTI_BASE:$DebVer
MULTI_NAME=epi_multi_php

if docker ps | grep $MULTI_NAME >/dev/null; then
    echo "Stopping the running '$MULTI_NAME' container..."
    docker stop -t 5 $MULTI_NAME >/dev/null
    while docker ps | grep $MULTI_NAME >/dev/null
    do
	sleep 1
    done
fi
if docker ps -a | grep $MULTI_NAME >/dev/null; then
    echo "Deleting the existing '$MULTI_NAME' container..."
    docker rm $MULTI_NAME >/dev/null
fi

test -d $Logs || mkdir -p $Logs
if docker images | grep "$MULTI_BASE *$DebVer" >/dev/null; then
    echo "Re-using the existing '$MULTI_IMG' image. Use:\n    docker rmi $MULTI_IMG\nto force a rebuild."
else
    echo "Building the '$MULTI_IMG' image..."
    #
    #   Find the waitpid package
    #
    WaitPkg=`ls $DistDir/tools/epi-tools-waitpid_*_amd64.deb 2>/dev/null`
    if [ -z "$WaitPkg" ]; then
	$TlsTop/bake $DebNum
	WaitPkg=`ls $DistDir/tools/epi-tools-waitpid_*_amd64.deb 2>/dev/null`
	if [ -z "$WaitPkg" ]; then
	    echo "$Prg: cannot build the waitpid package, needed to build the '$MULTI_IMG' image" >&2
	    exit 1
	fi
    fi
    cp -p $WaitPkg ${MulTop}run
    Pkg=`basename $WaitPkg`
    MULCOPY="COPY ${MulTop}run/start $MULTI_TOP/start
COPY ${MulTop}run/$Pkg /tmp
RUN dpkg -i /tmp/$Pkg; rm -v /tmp/$Pkg"
    #   Variables come in order of their appearance in Dockerfile-multi.in
    DEBVER="$DebVer" MULTI_TOP="$MULTI_TOP" MULTI_REQ="$MULTI_REQ" MULCOPY="$MULCOPY" envsubst '$DEBVER $MULTI_TOP $MULTI_REQ $MULCOPY' <${MulTop}Dockerfile.in | tee $Logs/Dockerfile-multi | docker build -f - -t $MULTI_IMG . >$Logs/docker-build.out 2>&1
    rm -f ${MulTop}run/epi-tools-waitpid_*.deb
fi
#
#   Run container
#
test "$HOSTFMT" && RunEnv=' -e HOSTFMT'
RunCmd()
{
    echo "docker run $1$RunEnv -p 80:80 -v `realpath $PWD/$MultDir`:$MULTI_TOP/work --name $MULTI_NAME --rm $MULTI_IMG"
}
if [ -f ${TopDir}.norun ]; then
    echo "Use:\n    `RunCmd -ti` bash\nto run the container"
else
    echo "Running the '$MULTI_NAME' container in background mode:\n    `RunCmd -d`"
    `RunCmd -d` >/dev/null
    while :
    do
	sleep 1
	grep '^Waiting for container stop' $Logs/docker-run.out >/dev/null && break
    done
    nd=`expr '(' $nd '*' 3 ')' + 1`
    sed -n "1,${nd}p" $Logs/docker-run.out
    echo "Use:\n    docker stop $MULTI_NAME\nto stop the container, and use:"
    echo "    `RunCmd -ti` bash\nto run the container in the foreground"
fi
