FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV DEBNUM=$DEBNUM
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN $ADDUSER
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -Al'\necho \"Use:\n    $MULTI_TOP/start\\nto start Apache\"" >>/root/.bashrc

# Update/upgrade, install tools and multi deps
RUN apt-get update && apt-get upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $MULTI_REQ

RUN mkdir -p $MULTI_TOP/conf
$MULCOPY

CMD [ "$MULTI_TOP/start" ]
