#!/bin/sh
#
#	01-cli/install - Install php-cli files to $Top
#
Phar='install-pear-nozlib.phar'
Pear=$Top/$PearDir
if grep metadata_dir pear/$Phar >/dev/null; then
    sed -i "s;$Phar -d;$Phar -m /$PearDir -D /$DocDir/$Name -M /$ManDir -d;" Makefile
fi
mkdir -p $Pear
# Skip install-sapi install-build install-headers install-pdo-headers
for tgt in install-cli install-binaries install-programs install-modules install-pear install-pharcmd
do
    grep "^install_targets = .* $tgt" Makefile >/dev/null && Tgts="$Tgts $tgt"
done
test "$Dbg" && echo "Tgts=\"$Tgts\""
INSTALL_ROOT=$Top PHP_PEAR_SYSCONF_DIR=etc/pear make$Tgts >$Logs/make-install_$Pkg.out 2>&1

MoveFiles()
{
    # global Bld Top Logs
    local Dir File Pkg Must Cmnt Name Path New Log

    while read Dir File Pkg Must Cmnt
    do
	test "$Dir" || continue					# Empty line
	expr "$Dir" : '[ 	]*#.*' >/dev/null && continue	# Comment 
	if [ ! -d $Bld/pkgs/$Pkg ]; then
	    echo "\aERROR: no Pkg=$Pkg in $Bld/pkgs (Dir=$Dir File=$File)"
	    continue
	fi
	test -f $Bld/pkgs/$Pkg/skip && continue
	Name=`expr "$Pkg" : '[0-9][0-9]-\(.*\)'`
	if [ ! -d $Top/$Dir ]; then
	    test "$Must" = 'y' && echo "\aERROR: no Dir=$Dir in $Top (File=$File Pkg=$Pkg)"
	    continue
	fi
	Path=`cd $Top; find $Dir -type f -name $File`
	if [ "$Path" -a -f "$Top/$Path" ]; then
	    New=$Bld/pkgs/$Pkg/top/`dirname $Path`
	    test -d $New || mkdir -p $New
	    Log=$Logs/make-install_$Name.out
	    test -f $Log || echo "Installing $Name package" >$Log
	    mv -v $Top/$Path $New >>$Log 2>&1
	elif [ "$Must" = 'y' ]; then
	    echo "\aERROR: no Path found in $Top for Dir=$Dir File=$File (Pkg=$Pkg)"
	    echo "Directory $Dir contains:"
	    (cd $Top; find $Dir -type f)
	fi
    done <$1
}

MoveFiles $dir/moves

if [ -d pear/man ]; then
    cp -rp pear/man $Top/usr/share
    find $Top/$ManDir -name '*.[1-9]' | xargs gzip -n9
else
    echo "\aERROR: no directory pear/man in `pwd`"
fi

>$Logs/rmed_$Pkg.out

#   Cleanup PEAR (mostly 1.9.1) junk
rm -vf $Top/.filemap $Top/.depdb* $Top/.lock $Pear/.depdb* $Pear/.lock >>$Logs/rmed_$Pkg.out
for d in .channels .registry; do
    test -d $Top/$d || continue
    (cd $Top; find $d -type f | while read f; do
	test -f $Pear/$f && cmp $Top/$f $Pear/$f >/dev/null && rm -v $Top/$f
    done)
    find $Top/$d -depth -type d | xargs rmdir -v
done >>$Logs/rmed_$Pkg.out
rmdir -v $Pear/.registry/.channel.* >>$Logs/rmed_$Pkg.out

test -d $Top/$VarDir && find $Top/$VarDir -depth -type d | xargs -r rmdir -v >>$Logs/rmed_$Pkg.out

file $Top/usr/bin/* | sed -n 's/^\([^:]*\): *ELF .*$/\1/p' | xargs -r strip -v >$Logs/striped_$Pkg.out
find $Top -name '*.so' | xargs -r strip -v >>$Logs/striped_$Pkg.out
find $Top -name '*.so' | xargs -r chmod -x
find $Top -name '*.sh' | xargs -r chmod +x
