#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives --install /usr/bin/php php /usr/bin/php%MM% %PRI% --slave /usr/share/man/man1/php.1.gz php.1.gz /usr/share/man/man1/php%MM%.1.gz
    update-alternatives --install /usr/bin/phar phar /usr/bin/phar%MM% %PRI% --slave /usr/share/man/man1/phar.1.gz phar.1.gz /usr/share/man/man1/phar%MM%.1.gz
    update-alternatives --install /usr/bin/phar.phar phar.phar /usr/bin/phar%MM%.phar %PRI% --slave /usr/share/man/man1/phar.phar.1.gz phar.phar.1.gz /usr/share/man/man1/phar%MM%.phar.1.gz
    update-alternatives --install /usr/lib/php/extensions extensions /usr/lib/php/%MM% %PRI%

    mkdir -p /etc/php/%MM%/conf.d
fi

if [ -d /etc/epiconcept/php-mods-available ]; then
    for f in /etc/epiconcept/php-mods-available/*.ini; do
	test -f $f && ln -fs $f /etc/php/%MM%/conf.d
    done
fi
