#!/bin/sh

export PHP_INI_DIR="/etc/php"
exit 0

fileArkPHP=/tmp/php.tar.bz2
cheminPack=/opt/debbuild

if [ ! -f php.tar.bz2 ]; then 
	curl -SL "http://fr2.php.net/get/php-7.1.11.tar.bz2/from/this/mirror" -o $fileArkPHP
fi

rm -rf /usr/src/php
mkdir -p /usr/src/php
tar -xf $fileArkPHP -C /usr/src/php --strip-components=1
cd /usr/src/php

./configure	\
	--prefix=/opt/debbuild/usr \
	--with-config-file-path="$PHP_INI_DIR" \
	--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
	--with-libdir=/lib/x86_64-linux-gnu\
	--with-bz2 \
	--with-curl \
	--enable-ctype \
	--enable-ftp \
	--with-gd \
	--enable-gd-native-ttf \
	--with-jpeg-dir=/usr --with-png-dir=/usr \
	--with-freetype-dir=/usr \
	--with-xpm-dir=/usr,/usr/X11R6 \
	--with-zlib-dir=/usr \
	--with-gettext \
	--enable-json \
	--enable-oauth \
	--enable-hash \
	--with-iconv \
	--enable-libxml \
	--enable-dom \
	--enable-mbstring \
	--with-mcrypt \
	--with-mhash \
	--with-pcre-regex \
	--enable-pdo \
	--with-pdo-mysql=/usr \
	--with-mysqli=/usr/bin/mysql_config \
	--with-libdir=lib \
	--with-openssl \
	--enable-posix \
	--enable-session \
	--enable-sockets \
	--enable-sysvmsg \
	--enable-sysvsem \
	--enable-sysvshm \
	--enable-xml \
	--enable-xmlreader \
	--enable-xmlwriter \
	--with-xsl \
	--enable-simplexml \
	--enable-soap \
	--enable-wddx \
	--enable-zip \
	--with-zlib \
	--disable-debug \
	--enable-bcmath

make -j"$(nproc)"

make install
INSTALL_ROOT=/opt/debbuild make install

make clean

cheminPack=/opt/debbuild
cp -r /paquet/* $cheminPack
find $cheminPack -type d -exec chmod 755 {} \;
find $cheminPack -type f ! -path "${cheminPack}/DEBIAN/*" ! -path "${cheminPack}/usr/local/bin/*" -exec chmod 644 {} \;
chmod 755 ${cheminPack}/DEBIAN/*
chmod 755 $cheminPack/usr/bin/* 
rm -rf $cheminPack$cheminPack
sortie=$(fakeroot dpkg-deb -Zgzip --build $cheminPack /opt/output/)
fichier=$(echo $sortie | grep "building package" | sed -e "s/.*in '//g" -e 's/deb.*/deb/g')
echo -e $sortie

lintian $fichier
