#!/bin/sh
#
#	03-fpm/install - Install php-fpm files to $Top
#
if [ -d $Top/usr/sbin ]; then
    file $Top/usr/sbin/* | sed -n 's/^\([^:]*\): *ELF .*$/\1/p' | xargs -r strip -v >$Logs/striped_$Pkg.out
else
    echo "\aERROR: no $Top/usr/sbin directory. Package will be useless."
fi
find $Top/$ManDir -name '*.[1-9]' | xargs gzip -n9
#   Replace link to w3.org icon with an embedded 26-byte GIF image
sed -i 's|src="http://www.w3.org/Icons/valid-xhtml10"|src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="|' $Top/$DataDir/fpm/status.html
