#!/bin/sh

set -e

if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
    update-alternatives --remove php-config /usr/bin/php-config%MM%
    update-alternatives --remove phpize /usr/bin/phpize%MM%
fi
