#!/bin/sh
#
#	04-mysql/install - Install php-mysql files to $Top
#
# There is no 'make install-..': files were moved to $Top by 00-cli/install
#
if [ -d $Top/usr/lib ]; then
    find $Top/usr/lib -name '*.so' | xargs -r strip -v >>$Logs/striped_$Pkg.out
    find $Top/usr/lib -name '*.so' | xargs -r chmod -x
else
    echo "\aERROR: no $Top/usr/lib directory. Package will be useless."
fi
sed -i -e "s/%MM%/$MM/g" -e "s;%MMD%;$MMD;" $Top/DEBIAN/postinst
sed -i -e "s/%MM%/$MM/g" -e "s;%MMD%;$MMD;" $Top/DEBIAN/postrm
