FROM debian:$DEBVER
LABEL maintainer Epiconcept

ENV DEBVER=$DEBVER
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN $ADDUSER
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -Al'\necho \"Use: $MYPKG_TOP/build\\nto build the packages\"" >>/root/.bashrc

# Update/upgrade, install tools and tools deps
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends vim file make fakeroot lintian manpages-dev

RUN mkdir -p $MYPKG_TOP/src $MYPKG_TOP/dist
$PKGCOPY

CMD [ "$MYPKG_TOP/build" ]
