#!/bin/sh
#
#	start - Install multiple PHP versions in virtual hosts and start Apache
#
Prg=`basename $0`
Dir=`dirname $0`
Conf='conf'
Logs="$Dir/$Conf/logs"
Pkgs="$Dir/$Conf/pkgs"
WWW="$Dir/www"
Base='epi-php'
Arch='amd64'
PkgDeb="+deb$DEBNUM"
IpSite="http://ipaddr.free.fr"
Own="$USER:`id -gn $USER`"
mkdir -p $Logs
test $$ -eq 1 && exec >$Logs/docker-run.out 2>&1
chown $Own $Logs/docker-run.out

set -e	# Stop on errors

if [ ! -d $Pkgs ]; then
    echo "$Prg: directory $Pkgs is missing" >&2
    exit 1
fi

Dists="`ls $Pkgs | sed -nr "s/$Base-[5-9]\.[0-9]-(cli|fpm|mysql)_([5-9]\.[0-9]\.[0-9]{,2}-[0-9]{,2})\\\\${PkgDeb}_$Arch.deb/\2/p" | sort -u`"
if [ -z "$Dists" ]; then
    echo "$Prg: no valid package name in $Pkgs" >&2
    exit 1
fi

if [ ! -e /sbin/runlevel ]; then	# Needed by invoke-rc.d
    echo "#!/bin/sh\necho \"${PREVLEVEL:-N} ${RUNLEVEL:-5}\"" >/sbin/runlevel
    chmod +x /sbin/runlevel
fi
test -x /usr/sbin/policy-rc.d && grep 'exit 101' /usr/sbin/policy-rc.d >/dev/null && sed -i 's/exit 101/exit 104/' /usr/sbin/policy-rc.d 

sed -i '1iServername localhost' /etc/apache2/sites-available/000-default.conf
a2enmod proxy_fcgi >$Logs/a2.out
>$Logs/dpkg-i.out
chown $Own $Logs/a2.out $Logs/dpkg-i.out

InFile="$Conf/siteconf.in"
InPath="$Dir/$InFile"
if [ -s "$InPath" ]; then
    echo "Using the existing $InFile for site configuration"
else
    # File default is here and not in multi/bake to include it in the docker images
    echo "Creating a default $InFile for site configuration"
    echo "#
#   Template for multi-PHP site configuration
#
#	%Maj% will be replaced by the PHP major version
#	%Min% will be replaced by the PHP minor version
#
#   DO NOT change DocumentRoot, it is needed by the container's start script
#   DO NOT change SetHandler, it is in sync with the PHP-FPM configuration
#
<VirtualHost *:80>
    ServerName php%Maj%%Min%.epiconcept.tld
    DocumentRoot $WWW
    <FilesMatch \".+\.ph(ar|p|tml)$\">
        SetHandler \"proxy:unix:/run/php/php%Maj%.%Min%-fpm.sock|fcgi://localhost\"
    </FilesMatch>
    <Directory $WWW>
	AllowOverride all
	Require all granted
    </Directory>
</VirtualHost>" >$InPath
    chown $Own $InPath
fi

ns=0
rm -f $Logs/*.conf
for dist in $Dists
do
    eval `echo "$dist" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})-([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
    if [ -s $Pkgs/$Base-$Maj.$Min-cli_$dist${PkgDeb}_$Arch.deb -a -s $Pkgs/$Base-$Maj.$Min-fpm_$dist${PkgDeb}_$Arch.deb ]; then
	dpkg -i $Pkgs/$Base-$Maj.$Min-cli_$dist${PkgDeb}_$Arch.deb $Pkgs/$Base-$Maj.$Min-fpm_$dist${PkgDeb}_$Arch.deb >>$Logs/dpkg-i.out
	test -s $Pkgs/$Base-$Maj.$Min-mysql_$dist${PkgDeb}_$Arch.deb && dpkg -i $Pkgs/$Base-$Maj.$Min-mysql_$dist${PkgDeb}_$Arch.deb >>$Logs/dpkg-i.out
	echo "----------------------------------------" >>$Logs/dpkg-i.out
    else
	echo "$Prg: cannot find both cli and fpm packages for $dist"
	continue
    fi
    SiteConf="`cat $InPath | sed -e "s/%Maj%/$Maj/g" -e "s/%Min%/$Min/g"`"
    Serv="`echo "$SiteConf" | sed -nr 's/^ *ServerName +([^ ]+).*$/\1/p'`"
    Hand="`echo "$SiteConf" | sed -nr 's/^ *SetHandler +([^ ]+).*$/\1/p'`"
    if echo " $Srvs" | grep " $Serv " >/dev/null; then
	echo "Discarded ServerName \"$Serv\""
	echo "    as it was already specified"
	continue
    fi
    echo "$SiteConf" >/etc/apache2/sites-available/$Serv.conf
    su -c "cp -p /etc/apache2/sites-available/$Serv.conf $Logs" $USER
    a2ensite $Serv.conf >>$Logs/a2.out
    echo "Added site http://$Serv"
    echo "    with SetHandler   $Hand"
    Srvs="$Srvs$Serv "
    ns=`expr $ns + 1`
done
IPAddr="`curl -sSL "$IpSite" 2>/dev/null | awk 'NR == 1 {print "IP=" $0} NR==2 { print "NS=" $0}'`"
if [ "$IPAddr" ]; then
    eval "$IPAddr"
    echo "Our public IP address is $IP ($NS)"
fi
if [ $ns -le 0 ]; then
    echo "$Prg: no valid site to start" >&2
    exit 1
fi
service apache2 restart >>$Logs/a2.out
test $$ -eq 1 && exec waitpid
