#!/bin/sh
#
#	build - Compile and build all packages in pkgs
#
Prg=`basename $0`
Bld=`dirname $0`
Logs="$Bld/dist/.logs"				# Directory for log files
test -f $Bld/.debug -o "$1" = 'debug' && Dbg=y
Own="$USER:`id -gn $USER`"

set -e	# Stop on errors

Base='epi-tests'
for dir in $Bld/pkgs/*
do
    PkgDir=`basename $dir`
    case $PkgDir in
	00-*)	Pkg=`expr "$PkgDir" : '[0-9]\{2\}-\(.*\)'`;;
	*)	echo "Ignoring the $PkgDir package directory" >&2;;
    esac
    test "$Pkg" || continue

    Top=$dir/top
    eval "$PKGDATA"
    PkgName="$Base-$PkgBin"

    echo "Installing package '$Pkg'..."

    # doc directory
    DocDir=$Top/usr/share/doc/pkgname
    sed -i "s/%YEAR%/`date '+%Y'`/" $DocDir/copyright
    sed -i -e "s/%NAME%/$PkgName/g" -e "s/%VERSION%/$PkgVer/" -e "s/%DEBVER%/$DEBVER/" -e "s/%PKGBIN%/$PkgBin/" -e "s/%DATE%/`date -Rr $Top/DEBIAN/control`/" $DocDir/changelog.Debian
    sed -i "s/%PKGBIN%/$PkgBin/" $DocDir/changelog
    gzip -n9 $DocDir/changelog*
    mv $DocDir $Top/usr/share/doc/$PkgName

    # lintian overrides
    LintDir=$Top/usr/share/lintian/overrides
    if [ -f $LintDir/pkgname ]; then
	sed -i -e "s/%NAME%/$PkgName/g" $LintDir/pkgname
	mv $LintDir/pkgname $LintDir/$PkgName
    fi

    # specific package install
    . $dir/install $PkgBin

    # DEBIAN directory
echo "PkgName=$PkgName PkgVer=$PkgVer PkgBin=$PkgBin"
    sed -i -e "s/%NAME%/$PkgName/" -e "s/%VERSION%/$PkgVer/" -e "s/%PKGBIN%/$PkgBin/" $Top/DEBIAN/control
    for Fld in Depends Provides Conflicts
    do
	case $Fld in
	    Depends)	Val="$PkgDep";;
	    Provides)	Val="$PkgPrv";;
	    Conflicts)	Val="$PkgCfl";;
	esac
	if [ "$Val" ]; then
	    Tag=`echo $Fld | tr '[a-z]' '[A-Z]'`
	    echo Fld=$Fld sed -i "s/%$Tag%/$Val/" $Top/DEBIAN/control
	    sed -i "s/%$Tag%/$Val/" $Top/DEBIAN/control
	else
	    sed -i "/^$Fld: /d" $Top/DEBIAN/control
	fi
    done

    echo "Assembling package '$Pkg'..."
    out=$(fakeroot dpkg-deb -Zgzip --build $Top $Bld/dist)
    deb=$(echo $out | sed "s/^.*building package ['\`][^']*' in ['\`]\([^']*\)'\.$/\1/")

    if [ -f "$deb" ]; then
	echo "Checking   package '$Pkg': `basename $deb`..."
	lintian --allow-root $deb >$Logs/lintian_$Pkg.out
	chown $Own $deb
    else
	test "$Dbg" && echo "out=\"$out\" deb=\"$deb\""
    fi
    if [ "$Dbg" ]; then
	(cd $Top;
	 find . -type f | sed 's/^..//' | sort >$Logs/files_$Pkg
	 find . -type l | sed 's/^..//' | sort >$Logs/links_$Pkg)
	test -s $Logs/links_$Pkg || rm $Logs/links_$Pkg
	chown $Own $Logs/*_$Pkg
    fi
    chown $Own $Logs/*_$Pkg.out
done
