#!/bin/sh
#
#	build - Compile and build mypkg packages
#
Prg=`basename $0`
Bld=`dirname $0`
Own="$USER:`id -gn $USER`"
Dist="$Bld/dist"
Logs="$Dist/.logs"				# Directory for log files
Spec="$Dist/pkgspecs"

test -f $Dist/.debug -o "$1" = 'debug' && Dbg=y
mkdir -p $Logs
chown $Own $Dist $Logs

set -e	# Stop on errors

Base='epi-tests'
Top=$Bld/top
if [ ! -s "$Spec" ]; then
    echo "\aERROR: $Spec file is missing or empty" >&2
    exit 1
fi
while read Line
do
    eval `echo "$Line" | sed -nr 's/([^_]+)_([^:]+):([^:]*):([^:]*):([^:]*)/PkgBin="\1" PkgVer="\2" PkgDep="\3" PkgPrv="\4" PkgCfl="\5"/p'`
    if [ -z "$PkgBin" -o -z "$PkgVer" ]; then
	echo "\aWARNING: skipping invalid pkgspecs line \"$Line\"" >&2
	echo   " format: <name>_<version>:[<depends>]:[<provides>]:[<conflicts>]" >&2
	continue
    fi
    PkgName="$Base-$PkgBin"

    echo "Installing package '${PkgName}_$PkgVer'..."
    rm -rf $Top
    cp -rp $Bld/src $Top

    # bin directory
    BinDir=$Top/usr/bin
    mv $BinDir/pkgname $BinDir/$PkgBin

    # man directory
    ManSec=1
    ManDir=$Top/usr/share/man/man$ManSec
    PkgCap=`echo $PkgBin | tr '[a-z]' '[A-Z]'`
    sed -i -e "s/%PKGCAP%/$PkgCap/g" -e "s/%MANSEC%/$ManSec/g" -e "s/%PKGBIN%/$PkgBin/g" $ManDir/pkgname.$ManSec
    mv $ManDir/pkgname.$ManSec $ManDir/$PkgBin.$ManSec
    gzip -n9 $ManDir/$PkgBin.$ManSec

    # doc directory
    DocDir=$Top/usr/share/doc/pkgname
    sed -i "s/%YEAR%/`date '+%Y'`/" $DocDir/copyright
    sed -i -e "s/%NAME%/$PkgName/g" -e "s/%VERSION%/$PkgVer/" -e "s/%DEBVER%/$DEBVER/" -e "s/%PKGBIN%/$PkgBin/" -e "s/%DATE%/`date -Rr $Top/DEBIAN/control`/" $DocDir/changelog.Debian
    sed -i "s/%PKGBIN%/$PkgBin/" $DocDir/changelog
    gzip -n9 $DocDir/changelog*
    mv $DocDir $Top/usr/share/doc/$PkgName

    # lintian overrides
    LintDir=$Top/usr/share/lintian/overrides
    if [ -f $LintDir/pkgname ]; then
	sed -i -e "s/%NAME%/$PkgName/g" $LintDir/pkgname
	mv $LintDir/pkgname $LintDir/$PkgName
    fi

    # DEBIAN directory
    sed -i -e "s/%NAME%/$PkgName/" -e "s/%VERSION%/$PkgVer/" -e "s/%PKGBIN%/$PkgBin/" $Top/DEBIAN/control
    for Fld in Depends Provides Conflicts
    do
	case $Fld in
	    Depends)	Val="$PkgDep";;
	    Provides)	Val="$PkgPrv";;
	    Conflicts)	Val="$PkgCfl";;
	esac
	if [ "$Val" ]; then
	    Tag=`echo $Fld | tr '[a-z]' '[A-Z]'`
	    test "$Dbg" && echo "    Fld=$Fld Tag=$Tag Val=\"$Val\""
	    sed -i "s/%$Tag%/$Val/" $Top/DEBIAN/control
	else
	    test "$Dbg" && echo "    Fld=$Fld deleted"
	    sed -i "/^$Fld: /d" $Top/DEBIAN/control
	fi
    done

    echo "Assembling package '${PkgName}_$PkgVer'..."
    out=$(fakeroot dpkg-deb -Zgzip --build $Top $Dist)
    deb=$(echo $out | sed "s/^.*building package ['\`][^']*' in ['\`]\([^']*\)'\.$/\1/")

    if [ -f "$deb" ]; then
	echo "Checking   package '$PkgName': `basename $deb`..."
	lintian --allow-root $deb >$Logs/lintian_$PkgName.out
	chown $Own $deb
    else
	test "$Dbg" && echo "out=\"$out\" deb=\"$deb\""
    fi
    if [ "$Dbg" ]; then
	(cd $Top;
	 find . -type f | sed 's/^..//' | sort >$Logs/files_$PkgName
	 find . -type l | sed 's/^..//' | sort >$Logs/links_$PkgName)
	test -s $Logs/links_$PkgName || rm $Logs/links_$PkgName
    fi
    chown $Own $Logs/*_$PkgName*
done <$Spec
