#!/bin/sh

Top=`dirname $0`/top
Dir=`realpath $Top/../../..`
Ver=$1
Maj=`echo $Ver | awk -F. '{print $1}'`

test -d /usr/src/php && rm -rvf /usr/src/php/php-* || mkdir /usr/src/php
tar xf $Dir/files/php-$Ver.tar.bz2 -C /usr/src/php
cd /usr/src/php/php-$Ver

export PHP_INI_DIR="/etc/php"
./configure	\
	--prefix=$Top/usr \
	--with-config-file-path="$PHP_INI_DIR" \
	--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
	--with-libdir=/lib/x86_64-linux-gnu \
	--with-apxs2=/usr/bin/apxs \
	--with-bz2 \
	--with-curl \
	--enable-ctype \
	--enable-ftp \
	--with-gd \
	--enable-gd-native-ttf \
	--with-jpeg-dir=/usr --with-png-dir=/usr \
	--with-freetype-dir=/usr \
	--with-xpm-dir=/usr,/usr/X11R6 \
	--with-zlib-dir=/usr \
	--with-gettext \
	--enable-json \
	--enable-hash \
	--with-iconv \
	--enable-libxml \
	--enable-dom \
	--enable-mbstring \
	--with-mcrypt \
	--with-mhash \
	--with-pcre-regex \
	--enable-pdo \
	--with-pdo-mysql=/usr \
	--with-mysqli=/usr/bin/mysql_config \
	--with-libdir=lib \
	--with-openssl \
	--enable-posix \
	--enable-session \
	--enable-sockets \
	--enable-sysvmsg \
	--enable-sysvsem \
	--enable-sysvshm \
	--enable-xml \
	--enable-xmlreader \
	--enable-xmlwriter \
	--with-xsl \
	--enable-simplexml \
	--enable-soap \
	--enable-wddx \
	--enable-zip \
	--with-zlib \
	--disable-debug \
	--enable-bcmath \
>$Dir/dist/config.out 2>&1

make >$Dir/dist/make.out 2>&1

touch $Top/etc/apache2/mods-available/apache2.conf
make install
INSTALL_ROOT=$Top make install >$Dir/dist/make-install.out 2>&1
rm $Top/etc/apache2/mods-available/apache2.conf

make clean >$Dir/dist/make-clean.out 2>&1

sed -i "s/%VERSION%/$Ver/" $Top/DEBIAN/control
sed -i "s/%PHPMAJ%/$Maj/" $Top/DEBIAN/postinst
sed -i "s/%PHPMAJ%/$Maj/g" $Top/etc/apache2/mods-available/php.load.us
mv $Top/etc/apache2/mods-available/php.load.us $Top/etc/apache2/mods-available/php$Maj.load.us
mv $Top/etc/apache2/mods-available/php.conf $Top/etc/apache2/mods-available/php$Maj.conf
find $Top/opt -depth -type d | xargs rmdir
#sed -i $Top/etc/apache2/mods-available/php7.load -e "s#/opt/debbuild##"
#find $cheminPack -type d -exec chmod 755 {} \;
#find $cheminPack -type f ! -path "${cheminPack}/DEBIAN/*" ! -path "${cheminPack}/usr/local/bin/*" -exec chmod 644 {} \;
#chmod 755 ${cheminPack}/DEBIAN/*
#chmod 755 $cheminPack/usr/bin/*
out=$(fakeroot dpkg-deb -Zgzip --build $Top $Dir/dist | tee $Dir/dist/dpkg-deb.out)
file=$(echo $out | grep "building package" | sed -e "s/.*in '//g" -e 's/deb.*/deb/g')
echo -e $out

lintian $file
