FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV DEBVER=$DEBVER
ENV LANG=C
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -al'\necho \"Use: $TOOLS_TOP/build\\nto build the packages\"" >>/root/.bashrc

# Update/upgrade
RUN apt-get update
RUN apt-get upgrade -y

# Tools and build deps
RUN apt-get install -y --no-install-recommends vim file gcc libc-dev make fakeroot lintian manpages-dev

RUN mkdir -p $TOOLS_TOP/pkgs $TOOLS_TOP/dist
COPY pkgs $TOOLS_TOP/pkgs
COPY build $TOOLS_TOP

CMD $TOOLS_TOP/build
