FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV DEBVER=$DEBVER
ENV DEBNUM=$DEBNUM
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN $ADDUSER
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -Al'\necho \"Use: $TOOLS_TOP/build\\nto build the packages\"" >>/root/.bashrc

# Update/upgrade, install tools and tools deps
RUN apt-get update && apt-get upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends vim file gcc libc-dev make fakeroot lintian manpages-dev

RUN mkdir -p $TOOLS_TOP/pkgs $TOOLS_TOP/dist
$TLSCOPY

CMD [ "$TOOLS_TOP/build" ]
