#!/bin/sh
#
#	tests - Test packages in $Tst/dist
#
Prg=`basename $0`
Tst=`dirname $0`
Logs="$Tst/dist/.logs"
Pkgs="$Tst/dist/.pkgs"
Dbg="$Tst/dist/.debug"
test -d $Dbg || Dbg=
LF='
'
unset HTTP_PROXY http_proxy

#  AddVar var val [sep]
AddVar()
{
   # global $1
   local sep

   sep=${3:-\\n}
   eval "test \"\$$1\" && $1=\"\${$1}$sep$2\" || $1=\"$2\""
}

set -e	# Stop on errors

if [ ! -f $Pkgs ]; then
    echo "$Prg: cannot find $Pkgs file" >&2
    exit 1
fi
Own="$USER:`id -gn $USER`"
umask 022

if [ ! -x /sbin/runlevel ]; then	# Needed by invoke-rc.d
    echo "#!/bin/sh\necho \"${PREVLEVEL:-N} ${RUNLEVEL:-5}\"" >/sbin/runlevel
    chmod +x /sbin/runlevel
fi
test -x /usr/sbin/policy-rc.d && grep -q 'exit 101' /usr/sbin/policy-rc.d && sed -i 's/exit 101/exit 104/' /usr/sbin/policy-rc.d
debinfo -a >$Logs/debinfo-a_tests
chown $Own "$Logs/debinfo-a_tests"

echo "Setting Apache 2 to prefork mode..."
sed -i '1iServername localhost' /etc/apache2/sites-available/000-default.conf
a2dismod mpm_event >$Logs/a2.out 2>&1
a2enmod mpm_prefork >>$Logs/a2.out 2>&1
echo "--- init-done -----" >>$Logs/a2.out

echo "Installing packages:"
test -d $Tst/pkgs && dpkg -i $Tst/pkgs/*.deb >$Logs/dpkg-i.out 2>&1 || >$Logs/dpkg-i.out

set +e
#   We do not have a real /sbin/init running
#   so process start/stop needs precautions
ApaCtl='/usr/sbin/apache2ctl'
test "$Dbg" && >$Dbg/ps-ef.out
while read Deb
do
    Pkg=`echo $Deb | awk -F_ '{print $1}'`
    if dpkg -l $Pkg >/dev/null 2>&1; then
	echo "  . $Deb is already installed."
	continue
    fi
    test "$Dbg" && (echo "--- pre-dpkg $Pkg -----"; ps -ef) >>$Dbg/ps-ef.out 2>&1
    echo "----------------------------------------" >>$Logs/dpkg-i.out
    Out="`dpkg -i $Tst/dist/$Deb 2>&1`"
    xc=$?
    if [ $xc -gt 0 ]; then
	Cfl=`echo "$Out" | sed -nr 's/^ ([^ ]*) conflicts with.*$/\1/p'`
	if [ "$Cfl" ]; then
	    Out="$Out$LF    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	    Out="$Out$LF`dpkg -P $Cfl 2>&1`"
	    echo "  ~ $Cfl removed as conflicting with $Pkg"
	    Out="$Out$LF    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
	    Out="$Out$LF`dpkg -i $Tst/dist/$Deb 2>&1`"
	    xc=$?
	fi
    fi
    echo "$Out" >>$Logs/dpkg-i.out
    if [ $xc -eq 0 ]; then
	echo "  - $Deb"
	case "$Pkg" in
	    *-cli)  echo -n "    Testing PHP CLI... "
		    php /var/www/html/info.php >$Logs/info_cli.out
		    test -s $Logs/info_cli.out || AddVar TestPkg $Pkg
		    echo "done."
		    ;;
	    *-mod)  echo -n "    Testing PHP Apache module... "
		    echo "--- mod-inst-done -----" >>$Logs/a2.out
		    test "$Dbg" && (echo --- post-install -----; ps -ef) >>$Dbg/ps-ef.out 2>&1
		    curl -sSL http://localhost/info.php >$Logs/info_mod.out
		    test -s $Logs/info_mod.out || AddVar TestPkg $Pkg
		    $ApaCtl stop >>$Logs/a2.out 2>&1
		    echo "--- mod-stop-done -----" >>$Logs/a2.out
		    sleep 1
		    echo "done."
		    ;;
	    *-fpm)  echo -n "    Testing PHP Apache FPM... "
		    echo "--- fpm-inst-done -----" >>$Logs/a2.out
		    a2enmod proxy_fcgi >>$Logs/a2.out 2>&1
		    a2enconf $Pkg >>$Logs/a2.out 2>&1
		    $ApaCtl restart >>$Logs/a2.out 2>&1
		    echo "--- fpm-restart-done -----" >>$Logs/a2.out
		    sleep 1
		    test "$Dbg" && (echo --- post-restart -----; ps -ef) >>$Dbg/ps-ef.out 2>&1
		    curl -sSL http://localhost/info.php >$Logs/info_fpm.out
		    test -s $Logs/info_fpm.out || AddVar TestPkg $Pkg
		    rc=/etc/init.d/php*-fpm
		    $rc stop >>$Logs/a2.out 2>&1
		    $ApaCtl stop >>$Logs/a2.out 2>&1
		    echo "--- fpm-stop-done -----" >>$Logs/a2.out
		    sleep 1
		    echo "done."
		    ;;
	esac
    else
	AddVar InstPkg $Pkg
    fi
    test "$Dbg" && (echo "--- post-dpkg $Pkg -----"; ps -ef) >>$Dbg/ps-ef.out 2>&1
done <$Pkgs
test "$Dbg" && chown $Own $Dbg/ps-ef.out
chown $Own $Logs/a2.out $Logs/dpkg-i.out $Logs/info_*.out
if [ "$InstPkg" ]; then
    echo "FAILED to install the following package(s):"
    echo "$InstPkg" | sed 's/^/    /'
    exit 2
elif [ "$TestPkg" ]; then
    echo "FAILED to test the following package(s):"
    echo "$TestPkg" | sed 's/^/    /'
    exit 2
fi
exit 0
