#!/bin/sh
#
#	Make PHP packages for a given set of PHP and Debian versions
#
#	Usage:	[php|.]/bake <PHP-version> [<Debian-version>]
#
#	PHP-version is checked to be available in PHP sources on $PHPSITE
#	Supported PHP versions are defined in debian/<Debian-version>/mkre
#	Debian-version is checked to be supported and defaults to latest version
#
PHPSITE='fr.php.net'
PHPARCH="museum.php.net/php5"
PECLGET="pecl.php.net/get"

Prg=php/`basename $0`
Dir=`dirname $0`
IniPwd=$PWD
TopDir=../
DebTop=${TopDir}debian
PhpTop=
PhpGit=php/

Path() { realpath --relative-to=$IniPwd $1; }
test "$Dir" || Dir=`dirname \`realpath $0\``
expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
test "$Dir" = '.' || cd "$Dir"
#   Script's CWD is where it is located, but all messages assume PWD is top-level
test -d $DebTop || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }

#
# Get existing PHP 5.x and 7.x versions
#
Versions="`curl -sSL "http://$PHPSITE/ChangeLog-5.php" "http://$PHPSITE/ChangeLog-7.php" | sed -n 's/^.*<h[1-4]>Version \([^ ]*\) *<\/h[1-4]>/\1/p' | sort -nr -t. -k 1,1 -k 2,2 -k 3,3`"
if [ -z "$Versions" ]; then
    echo "$Prg: unable to fetch the latest lists of PHP versions from \"$PHPSITE\"" >&2
    echo "$Prg: using instead the list of versions already known" >&2
    Versions="`ls -d $PhpTop[5-9]/[5-9].* | sed "s;^$PhpTop./;;" | sort -nr -t. -k 1,1 -k 2,2 -k 3,3`"
    if [ -z "$Versions" ]; then
	echo "$Prg: empty list of known PHP versions ??" >&2
	exit 1
    fi
fi
#
# From $Versions isolate latest rel for each Maj.min
#
Latest="`echo "$Versions" | awk -F. '{
    Mm = $1 "." $2
    if (Mm in v) {
	if (v[Mm] < $3)
	    v[Mm] = $3
    }
    else
	v[Mm] = $3
}
END {
    for (Mm in v)
	printf("%s.%s\n", Mm, v[Mm]);
}'`"

SupPhp()
{
    # global Latest
    local sup flt

    test "$1" && sup=" $1" || sup=
    test "$1" && flt="| grep -v '^5\.[01345]\.'" || flt=
    echo "Latest$sup PHP 5/7 versions:" >&2
    eval "echo \"$Latest\" $flt | sed 's/^/    /'" >&2
}

SupDeb()
{
    # global DebNum
    local v

    echo "Supported Debian versions (default $DebNum):" >&2
    ls $DebTop | sort -n | while read v; do test -f $DebTop/$v/name && printf "    %2d (`cat $DebTop/$v/name`)\n" $v; done >&2
}

#
#   Check usage
#
DebNum=`ls $DebTop | sort -n | tail -1`	# Default = latest
if [ $# -ne 1 -a $# -ne 2 ]; then
    echo "Usage: $Prg <PHP-version> [ <Debian-version> ]" >&2
    SupPhp supported
    SupDeb
    exit 1
fi

#
#   Check PHP version
#
split="`echo "$1" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3/p'`"
if [ -z "$split" ]; then
    echo "$Prg: invalid PHP version \"$1\" ([5-9].[0-9].[0-9]{,2})" >&2
    exit 1
fi
eval "$split"
if echo "$Versions" | grep "^$Maj\.$Min\.$Rel$" >/dev/null; then
    PhpVer="$1"
    PhpDir=$PhpTop$Maj/$PhpVer
else
    echo "$Prg: unknown PHP version \"$1\"" >&2
    SupPhp
    exit 1
fi

#
#   Check Debian version
#
if [ "$2" ]; then
    if [ -f $DebTop/$2/name ]; then
	DebNum="$2"
    else
	echo "$Prg: unsupported Debian version \"$2\"" >&2
	SupDeb
	exit 1
    fi
fi
DebVer="`cat $DebTop/$DebNum/name`"
DebDir=$DebTop/$DebNum
#echo "DebVer=$DebVer PhpVer=$PhpVer Maj=$Maj Min=$Min Rel=$Rel"

#
#   Fetch PHP source
#
date '+===== %Y-%m-%d %H:%M:%S %Z =================='
Now=`date '+%s'`
if [ ! -d $PhpDir ]; then
    mkdir -p $PhpDir
    mk=y
fi
Tbz=php-$PhpVer.tar.bz2
PhpSrc=$PhpDir/$Tbz
PhpLst=$PhpDir/php-$PhpVer.files
if [ ! -s $PhpSrc ]; then
    echo "Fetching $Tbz..."
    Url1="http://$PHPSITE/get/$Tbz/from/this/mirror"
    Url2="http://$PHPARCH/$Tbz"
    for Url in "$Url1" "$Url2"
    do
	echo "Trying from \"$Url\"..."
	curl -sSL "$Url" -o $PhpSrc 2>/dev/null
	test $? -eq 0 -a -s $PhpSrc && break
    done
    if [ -s $PhpSrc ]; then
	dl=y
    else
	echo "Failed to download $Tbz from known URLs" >&2
	echo "Put it manually as $PhpSrc and run $Prg again" >&2
	rm -f $PhpSrc
	test "$mk" && find $PhpDir -type d -empty -delete
	exit 1
    fi
fi
if [ ! -s $PhpLst ]; then
    if ! tar tf $PhpSrc >$PhpLst 2>/dev/null; then
	echo "$Prg: $PhpSrc is not recognized as a tar archive" >&2
	rm -f $PhpLst
	test "$dl" && rm $PhpSrc
	exit 1
    fi
fi
if ! grep "^php-$PhpVer/" $PhpLst >/dev/null; then
    echo "$Prg: $PhpSrc is not recognized as a PHP $PhpVer source archive" >&2
    test "$dl" && rm $PhpSrc $PhpLst
    exit 1
fi

#
#   Source debian and PHP hooks (in that order)
#
BUILD_TOP=/opt/php-mk
TESTS_TOP=/opt/php-mk

if [ -f $DebDir/Dockervars.sh ]; then
    . $DebDir/Dockervars.sh
else
    echo "$Prg: missing debian/$DebNum/Dockervars.sh" >&2
    exit 1
fi
if [ -f $PhpTop$Maj/Dockervars.sh ]; then
    . $PhpTop$Maj/Dockervars.sh	# NOTE: initializes BLDCOPY and possibly TSTCOPY
else
    echo "$Prg: missing php/$Maj/Dockervars.sh" >&2
    exit 1
fi

#
#   Determine build number and build date
#
Num=$PhpDir/BUILD_NUM
Cmt="`git log -n1 --format=%H -- $PhpGit$Num 2>/dev/null`"
if [ "$Cmt" ]; then
    Log=`git show $Cmt:$Num`
    if [ -f $Num ]; then	# If $Num exists and is $Log, set it's mtime to $Cmt's
	test "`cat $Num`" = "$Log" && touch -d "`git show -s --format=%ci $Cmt`" $Num
    else			# else set $Num = $Log + 1
	echo `expr $Log + 1` >$Num
    fi
else				# No log yet: keep $Num or create it if needed
    test -f $Num || echo 1 >$Num
fi
Bld=`cat $Num`			# For package names
Dist=$DebDir/dist/$PhpVer-$Bld
test -d $Dist || mkdir -p $Dist
touch -r $Num $Dist/.date	# For package dates in changelog.Debian

echo "Making PHP $PhpVer-$Bld packages for Debian $DebVer..."
echo "Logs will be in debian/$DebNum/dist/$PhpVer-$Bld/.logs/"
test -d $Dist/.logs && rm -f $Dist/.logs/*.out || mkdir $Dist/.logs

#
#   Make build image and start container
#
Tag=$DebVer-$PhpVer
BUILD_BASE=epi-build-php
BUILD_IMG=$BUILD_BASE:$Tag	# Keep all build images separate
BUILD_NAME=epi_build_php	# Only one build container at a time

BLDCOPY="$BLDCOPY
COPY $PhpSrc $BUILD_TOP/files
COPY ${PhpTop}pkgs $BUILD_TOP/pkgs
COPY ${PhpTop}run/build $BUILD_TOP"
test -f ${TopDir}.debug && BLDCOPY="$BLDCOPY
RUN >$BUILD_TOP/.debug"
test -f ${PhpTop}.notest && BLDCOPY="$BLDCOPY
RUN >$BUILD_TOP/.notest"

if docker ps | grep $BUILD_NAME >/dev/null; then
    echo "Stopping the running '$BUILD_NAME' container..."
    docker stop -t 5 $BUILD_NAME >/dev/null
    while docker ps | grep $BUILD_NAME >/dev/null
    do
	sleep 1
    done
fi
if docker ps -a | grep $BUILD_NAME >/dev/null; then
    echo "Deleting the existing '$BUILD_NAME' container..."
    docker rm $BUILD_NAME >/dev/null
fi
if docker images | grep "$BUILD_BASE *$Tag" >/dev/null; then
    echo "Deleting the existing '$BUILD_IMG' image..."
    docker rmi $BUILD_IMG >/dev/null
fi

echo "Building the '$BUILD_IMG' image..."
User=`id -un`
AddUser="groupadd -g `id -g` `id -gn`; useradd -u `id -u` -g `id -g` $User"
#   Variables come in order of their appearance in Dockerfile-build.in
DEBVER="$DebVer" CLI_DEPS="$CLI_DEPS" BUILD_NUM="$Bld" USER="$User" BUILD_TOP="$BUILD_TOP" ADDUSER="$AddUser" BUILD_REQ="$BUILD_REQ" BLDCOPY="$BLDCOPY" envsubst '$DEBVER $CLI_DEPS $BUILD_NUM $USER $BUILD_TOP $ADDUSER $BUILD_REQ $BLDCOPY' <${PhpTop}Dockerfile-build.in | tee $Dist/.logs/Dockerfile-build | docker build -f - -t $BUILD_IMG . >$Dist/.logs/docker-build.out 2>&1

Cmd="docker run -ti -v `realpath $PWD/$Dist`:$BUILD_TOP/dist --name $BUILD_NAME --rm $BUILD_IMG"
if [ -f ${TopDir}.norun ]; then
    echo "Use:\n    $Cmd bash\nto run the build container"
else
    echo "Running the '$BUILD_NAME' container:\n    $Cmd"
    $Cmd
fi
echo "------------------------------------------------"

#
#   Make tests image and start container
#
TESTS_BASE=epi-tests-php
TESTS_IMG=$TESTS_BASE:$Tag	# Keep all tests images separate
TESTS_NAME=epi_tests_php	# Only one tests container at a time

TSTCOPY="$TSTCOPY
COPY ${PhpTop}run/info.php /var/www/html
COPY ${PhpTop}run/tests $TESTS_TOP"

if docker ps | grep $TESTS_NAME >/dev/null; then
    echo "Stopping the running '$TESTS_NAME' container..."
    docker stop -t 5 $TESTS_NAME >/dev/null
    while docker ps | grep $TESTS_NAME >/dev/null
    do
	sleep 1
    done
fi
if docker ps -a | grep $TESTS_NAME >/dev/null; then
    echo "Deleting the existing '$TESTS_NAME' container..."
    docker rm $TESTS_NAME >/dev/null
fi
if docker images | grep "$TESTS_BASE *$Tag" >/dev/null; then
    echo "Deleting the existing '$TESTS_IMG' image..."
    docker rmi $TESTS_IMG >/dev/null
fi

echo "Building the '$TESTS_IMG' image..."
#   Variables come in order of their appearance in Dockerfile-tests.in
DEBVER="$DebVer" TESTS_TOP="$TESTS_TOP" TESTS_REQ="$TESTS_REQ" TSTCOPY="$TSTCOPY" envsubst '$DEBVER $TESTS_TOP $TESTS_REQ $TSTCOPY' <${PhpTop}Dockerfile-tests.in | tee $Dist/.logs/Dockerfile-tests | docker build -f - -t $TESTS_IMG . >$Dist/.logs/docker-tests.out 2>&1

Cmd="docker run -ti -v `realpath $PWD/$Dist`:$TESTS_TOP/dist --name $TESTS_NAME --rm $TESTS_IMG"
if [ -f ${TopDir}.norun ]; then
    echo "Use:\n    $Cmd bash\nto run the tests container"
else
    echo "Running the '$TESTS_NAME' container:\n    $Cmd"
    $Cmd
fi

#
#   End
#
date '+===== %Y-%m-%d %H:%M:%S %Z =================='
End=`date '+%s'`
Len=`expr $End - $Now`
Min=`expr $Len / 60`	# $Min above not needed anymore
Sec=`expr $Len - '(' $Min '*' 60 ')'`
printf "Duration: %d:%02d\n" $Min $Sec
