#!/bin/sh
#
#	Make PHP packages for a given set of PHP and Debian versions
#
#	Usage:	[php|.]/bake <PHP-version> [<Debian-version>]
#
#	PHP-version is checked to be available in PHP sources on $PHPSITE
#	Supported PHP versions are defined in debian/<Debian-version>/mkre
#	Debian-version is checked to be supported and defaults to latest version
#
PHPSITE='fr.php.net'
PHPARCH="museum.php.net/php5"
PECLGET="pecl.php.net/get"
Ext=.tar.bz2
LF='
'
tty <&1 >/dev/null && Opt='-ti '
ColRed=`tput setaf 1`
ColGrn=`tput setaf 2`
ColStd=`tput setaf 7`

Prg=php/`basename $0`
Dir=`dirname $0`
IniPwd=$PWD
TopDir=../
debTop='debian'		# For messages
DebTop=$TopDir$debTop
BinDir=${TopDir}bin
PhpTop=

Path() { realpath --relative-to=$IniPwd $1; }
test "$Dir" || Dir=`dirname \`realpath $0\``
expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
test "$Dir" = '.' || cd "$Dir"
#   Script's CWD is where it is located, but all messages assume PWD is top-level
test -d $DebTop || { echo "$Prg: missing '$debTop' directory." >&2; exit 1; }

#
# Get existing PHP 5.x and 7.x versions
#
Versions=`curl -sSL "http://$PHPSITE/ChangeLog-5.php" "http://$PHPSITE/ChangeLog-7.php" "http://$PHPSITE/ChangeLog-8.php" | sed -nr 's;^.*<h[1-4]>Version +([^ ]+) *</h[1-4]>;\1;p'`
test "$Versions" || echo "$Prg: unable to fetch the latest lists of PHP versions from \"$PHPSITE\"\n$Prg: using only the list of versions already known" >&2
Versions="$Versions$LF`ls -d $PhpTop[5-9]/[5-9].* | sed "s;^$PhpTop./;;"`"
Versions=`echo "$Versions" | sort -nru -t. -k 1,1 -k 2,2 -k 3,3`
if [ -z "$Versions" ]; then
    echo "$Prg: empty list of known PHP versions ??" >&2
    exit 1
fi
#
# From $Versions isolate latest rel for each Maj.min
#
Latest=`echo "$Versions" | awk -F. '{
    Mm = $1 "." $2
    if (Mm in v) {
	if (v[Mm] < $3)
	    v[Mm] = $3
    }
    else
	v[Mm] = $3
}
END {
    for (Mm in v)
	printf("%s.%s\n", Mm, v[Mm]);
}'`

#
#   Check usage
#
DebNum=`ls $DebTop/*/name | sed "s;$DebTop/\([^/]*\)/name;\1;" | sort -n | tail -1`	# Default = latest
if [ $# -ne 1 -a $# -ne 2 ]; then
    echo "Usage: $Prg <PHP-version> [ <Debian-version> ]" >&2
    exit 1
fi

#
#   Check PHP version
#
split=`echo "$1" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3/p'`
if [ -z "$split" ]; then
    echo "$Prg: invalid PHP version \"$1\" ([5-9].[0-9].[0-9]{,2})" >&2
    exit 1
fi
eval "$split"
if echo "$Versions" | grep "^$Maj\.$Min\.$Rel$" >/dev/null; then
    PhpVer="$1"
    PhpDir=$PhpTop$Maj/$PhpVer
else
    echo "$Prg: unknown PHP version \"$1\"" >&2
    echo "Latest PHP 5/7 versions:" >&2
    echo "$Latest" | sed 's/^/    /' >&2
    exit 1
fi

#
#   Check Debian version
#
if [ "$2" ]; then
    if [ -f $DebTop/$2/name ]; then
	DebNum="$2"
    else
	echo "$Prg: unsupported Debian version \"$2\"" >&2
	echo "Supported Debian versions (default $DebNum):" >&2
	ls $DebTop | sort -n | while read v; do test -f $DebTop/$v/name && printf "    %2d (`cat $DebTop/$v/name`)\n" $v; done >&2
	exit 1
    fi
fi
DebVer=`cat $DebTop/$DebNum/name`
DebDir=$DebTop/$DebNum
debDir=$debTop/$DebNum	# For messages
#echo "DebVer=$DebVer PhpVer=$PhpVer Maj=$Maj Min=$Min Rel=$Rel"

#
#   Fetch PHP source
#
test -f '.fetch' || date '+===== %Y-%m-%d %H:%M:%S %Z =================='
Now=`date '+%s'`
mk=
dl=
if [ ! -d $PhpDir ]; then
    mkdir -p $PhpDir
    mk=y
fi
#   ChkSrc SrcFile LstFile PhpVer - Check PHP source tarball
ChkSrc()
{
    # global Prg
    test -s $1 || return 1	# Safety check
    if [ ! -s $2 ]; then
	if ! tar tf $1 >$2 2>/dev/null; then
	    echo "$Prg: $1 is not recognized as a tar archive" >&2
	    rm -f $2
	    return 1
	fi
    fi
    grep "^php-$3/" $2 >/dev/null && return 0
    echo "$Prg: $1 is not recognized as a PHP $3 source archive" >&2
    return 1
}
Tbz=php-$PhpVer$Ext
PhpSrc=$PhpDir/$Tbz
PhpLst=$PhpDir/php-$PhpVer.files
if [ -s $PhpSrc ]; then		# $PhpSrc exists: check it
    ChkSrc $PhpSrc $PhpLst $PhpVer || exit 1
else
    echo "Fetching $Tbz..."
    Urls="http://$PHPSITE/get/$Tbz/from/this/mirror http://$PHPARCH/$Tbz"
    for Url in $Urls
    do
	echo "Trying from \"$Url\"..."
	if curl -sSL "$Url" -o $PhpSrc 2>/dev/null; then
	    if ChkSrc $PhpSrc $PhpLst $PhpVer; then
		dl=y
		break
	    fi
	fi
    done
    if [ -z "$dl" ]; then
	echo "$ColRed\aFAILED to download $Tbz from known URLs$ColStd" >&2
	echo "Put it manually as $PhpSrc and run $Prg again" >&2
	rm -f $PhpSrc $PhpLst
	test "$mk" && find $PhpDir -type d -empty -delete
	exit 1
    fi
fi
#
#   Determine build number and build date
#
Num=$PhpDir/BUILD_NUM
Cmt=`git log -n1 --format='%H' -- $Num 2>/dev/null`
if [ "$Cmt" ]; then
    Log=`git show "$Cmt:./$Num"`	# $Num is in git's log
    if [ -f $Num ]; then	# If $Num exists and is $Log, set it's mtime to $Cmt's
	test "`cat $Num`" = "$Log" && mt=y
    elif [ "$mk" ]; then	# If $PhpDir was just created, restore $Log and set mtime
	echo "$Log" >$Num; mt=y
    else			# If $Num missing in existing $PhpDir, set $Num = $Log + 1
	echo `expr "$Log" + 1` >$Num
    fi
    test "$mt" && touch -d "`git show -s --format=%ci $Cmt`" $Num
else				# No log yet: keep $Num or create it if needed
    test -f $Num || echo 1 >$Num
fi
test -f '.fetch' && exit 0

#
#   Source debian and PHP hooks (in that order)
#
BUILD_TOP=/opt/php-mk
TESTS_TOP=/opt/php-mk

if [ -f $DebDir/Dockervars.sh ]; then
    . $DebDir/Dockervars.sh
else
    echo "$Prg: missing $debDir/$DebNum/Dockervars.sh" >&2
    exit 1
fi
if [ -f $PhpTop$Maj/Dockervars.sh ]; then
    . $PhpTop$Maj/Dockervars.sh	# NOTE: initializes BLDCOPY and possibly TSTCOPY
else
    echo "$Prg: missing php/$Maj/Dockervars.sh" >&2
    exit 1
fi

#
#   Setup build
#
Bld=`cat $Num`			# For package names
Dist="dist/$PhpVer-$Bld"
RelDir=$DebDir/$Dist
relDir=$debDir/$Dist	# For messages
test -d $RelDir || mkdir -p $RelDir
touch -r $Num $RelDir/.date	# For package dates in changelog.Debian

echo "Making PHP $PhpVer-$Bld packages for Debian $DebVer..."
echo "Logs will be in $relDir/.logs/"
test -d $RelDir/.logs && rm -f $RelDir/.logs/*.out || mkdir $RelDir/.logs
User=`id -un`
test "$User" = 'php' && Type='epi' || Type='dev'
AddUser="groupadd -g `id -g` `id -gn`; useradd -u `id -u` -g `id -g` $User"

#
#   Make build image and start container
#
Tag=$DebVer-$PhpVer
BUILD_BASE=$Type-build-php
BUILD_IMG=$BUILD_BASE:$Tag	# Keep all build images separate
BUILD_NAME=$BUILD_BASE-${PhpVer}_$DebVer

BLDCOPY="$BLDCOPY
COPY $PhpSrc $BUILD_TOP/files
COPY ${PhpTop}pkgs $BUILD_TOP/pkgs
COPY ${PhpTop}run/build $BUILD_TOP
COPY ${PhpTop}run/bin /usr/local/bin"
test -f ${TopDir}.debug && BLDCOPY="$BLDCOPY
RUN >$BUILD_TOP/.debug"
test -f ${PhpTop}.notest && BLDCOPY="$BLDCOPY
RUN >$BUILD_TOP/.notest"

if docker ps | grep $BUILD_NAME >/dev/null; then
    echo "Stopping the running '$BUILD_NAME' container..."
    docker stop -t 5 $BUILD_NAME >/dev/null
    while docker ps | grep $BUILD_NAME >/dev/null
    do
	sleep 1
    done
fi
if docker ps -a | grep $BUILD_NAME >/dev/null; then
    echo "Deleting the existing '$BUILD_NAME' container..."
    docker rm $BUILD_NAME >/dev/null
fi
if docker images | grep "$BUILD_BASE *$Tag" >/dev/null; then
    echo "Deleting the existing '$BUILD_IMG' image..."
    docker rmi $BUILD_IMG >/dev/null
fi

echo "Building the '$BUILD_IMG' image..."
echo y | docker buildx prune >$RelDir/.logs/docker-build.out
if [ "$APT_SRC" ]; then
    $BinDir/aptsrv "$debDir" && AptSrv=y
elif [ "$http_proxy" -a "$https_proxy" ]; then
    BldArgs="--build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy"
fi
#   Variables come in order of their appearance in Dockerfile-build.in
DEBVER="$DebVer" DEBNUM="$DebNum" CLI_DEPS="$CLI_DEPS" BUILD_NUM="$Bld" USER="$User" ADDUSER="$AddUser" APT_SRC="$APT_SRC" BUILD_TOP="$BUILD_TOP" BUILD_REQ="$BUILD_REQ" BLDCOPY="$BLDCOPY" envsubst '$DEBVER $DEBNUM $CLI_DEPS $BUILD_NUM $USER $ADDUSER $APT_SRC $BUILD_TOP $BUILD_REQ $BLDCOPY' <${PhpTop}Dockerfile-build.in | tee $RelDir/.logs/Dockerfile-build | docker build -f - -t $BUILD_IMG $BldArgs . >>$RelDir/.logs/docker-build.out 2>&1

test -f ${TopDir}.norun && Opt='-ti '
if [ "$http_proxy" -a "$https_proxy" ]; then
    test "$APT_SRC" || Env="--env http_proxy=$http_proxy --env https_proxy=$https_proxy"
fi
if docker images | grep "$BUILD_BASE *$Tag" >/dev/null; then
    Cmd="docker run $Opt-v `realpath $PWD/$RelDir`:$BUILD_TOP/dist $Env --name $BUILD_NAME --rm $BUILD_IMG"
    if [ -f ${TopDir}.norun ]; then
	echo "Use:\n    $Cmd bash\nto run the build container"
    else
	echo "Running the '$BUILD_NAME' container:\n    $Cmd"
	if $Cmd; then
	    echo "Made PHP $PhpVer-$Bld packages for Debian $DebVer."
	else
	    echo "$ColRed\aFAILED to make PHP $PhpVer-$Bld packages for Debian $DebVer!$ColStd"
	    test "$AptSrv" && $BinDir/aptsrv 'stop'
	    exit 3
	fi
    fi
else
    echo "$ColRed\aFAILED to build the $BUILD_IMG image!$ColStd"
    echo "Examine $relDir/.logs/docker-build.out for details."
    test "$AptSrv" && $BinDir/aptsrv 'stop'
    exit 2
fi
echo "------------------------------------------------"

#
#   Make tests image and start container
#
TESTS_BASE=$Type-tests-php
TESTS_IMG=$TESTS_BASE:$Tag	# Keep all tests images separate
TESTS_NAME=$TESTS_BASE-${PhpVer}_$DebVer

TSTCOPY="$TSTCOPY
COPY ${PhpTop}run/info.php /var/www/html
COPY ${PhpTop}run/tests $TESTS_TOP"

if docker ps | grep $TESTS_NAME >/dev/null; then
    echo "Stopping the running '$TESTS_NAME' container..."
    docker stop -t 5 $TESTS_NAME >/dev/null
    while docker ps | grep $TESTS_NAME >/dev/null
    do
	sleep 1
    done
fi
if docker ps -a | grep $TESTS_NAME >/dev/null; then
    echo "Deleting the existing '$TESTS_NAME' container..."
    docker rm $TESTS_NAME >/dev/null
fi
if docker images | grep "$TESTS_BASE *$Tag" >/dev/null; then
    echo "Deleting the existing '$TESTS_IMG' image..."
    docker rmi $TESTS_IMG >/dev/null
fi

echo "Building the '$TESTS_IMG' image..."
#   Variables come in order of their appearance in Dockerfile-tests.in
DEBVER="$DebVer" USER="$User" ADDUSER="$AddUser" APT_SRC="$APT_SRC" TESTS_TOP="$TESTS_TOP" TESTS_REQ="$TESTS_REQ" TSTCOPY="$TSTCOPY" envsubst '$DEBVER $USER $ADDUSER $APT_SRC $TESTS_TOP $TESTS_REQ $TSTCOPY' <${PhpTop}Dockerfile-tests.in | tee $RelDir/.logs/Dockerfile-tests | docker build -f - -t $TESTS_IMG $BldArgs . >$RelDir/.logs/docker-tests.out 2>&1
test "$AptSrv" && $BinDir/aptsrv 'stop'

if docker images | grep "$TESTS_BASE *$Tag" >/dev/null; then
    Cmd="docker run $Opt-v `realpath $PWD/$RelDir`:$TESTS_TOP/dist $Env --name $TESTS_NAME --rm $TESTS_IMG"
    if [ -f ${TopDir}.norun ]; then
	echo "Use:\n    $Cmd bash\nto run the tests container"
    else
	echo "Running the '$TESTS_NAME' container:\n    $Cmd"
	if $Cmd; then
	    echo "${ColGrn}All PHP $PhpVer-$Bld packages for Debian $DebVer built and tested.$ColStd"
	else
	    echo "$ColRed\aFAILED to test PHP $PhpVer-$Bld packages for Debian $DebVer!$ColStd"
	    exit 3
	fi
    fi
else
    echo "$ColRed\aFAILED to build the $TESTS_IMG image!$ColStd"
    echo "Examine $relDir/.logs/docker-tests.out for details."
    exit 2
fi

#
#   End
#
date '+===== %Y-%m-%d %H:%M:%S %Z =================='
End=`date '+%s'`
Len=`expr $End - $Now`
Min=`expr $Len / 60`	# $Min above not needed anymore
Sec=`expr $Len - '(' $Min '*' 60 ')'`
printf "Duration: %d:%02d\n" $Min $Sec
