#!/bin/sh
#
#	build - Configure, compile and test from PHP source
#		Install and build all packages in pkgs
#
Prg=`basename $0`
Bld=`dirname $0`
Ver="$1"
Logs="$Bld/dist/.logs"
Pkgs="$Bld/dist/.pkgs"
Maj=`echo $Ver | awk -F. '{print $1}'`
Min=`echo $Ver | awk -F. '{print $2}'`
test "$2" = 'debug' -o -f $Bld/.debug && Dbg=y

set -e	# Stop on errors

# In dir $1, if $2 doesn't exist, link it to $3/$2
chkln()
{
   (test -d $1 || mkdir -p $1; cd $1; test -e $2 || ln -s $3/$2 $2)
}

echo "Extracting php-$Ver source..."
test -d /usr/src/php && rm -rf /usr/src/php
tar xf $Bld/files/php-$Ver.tar.bz2 -C /usr/src
mv /usr/src/php-$Ver /usr/src/php

cd /usr/src/php
ConfigHelp=$Logs/config-help.out
./configure --help >$ConfigHelp
for Opt in '--with-mysql' '--with-mcrypt' '--with-ttf' '--enable-gd-native-ttf' '--enable-fpm'
do
    case "$Opt" in
	--with-*)   Sep='[=[]';;
	*)	    Sep=' ';;
    esac
    if grep -- "$Opt$Sep" $ConfigHelp >/dev/null; then
	echo "Using ${Opt} option found in 'configure'"
	ExtOpts="$ExtOpts$Opt "
    fi
done
if grep -- "--enable-phpdbg " $ConfigHelp >/dev/null; then
    ExtOpts="$ExtOpts--disable-phpdbg "
fi
# Skip *-mysql package generation if --with-mysql known
echo "$ExtOpts" | grep -- '--with-mysql ' >/dev/null && >`ls -d $Bld/pkgs/*-mysql`/skip	
echo "$ExtOpts" | grep -- '--enable-fpm ' >/dev/null || >`ls -d $Bld/pkgs/*-fpm`/skip	

if [ -d $Bld/hooks ]; then
    for hook in $Bld/hooks/*
    do
	Show=
	Opt=
	. $hook
	if [ "$Show" ]; then
	    test "$HookShow" && HookShow="$HookShow + $Show" || HookShow=" with $Show"
	fi
	test "$Opt" && HookOpts="$HookOpts$Opt "
    done
    if [ "$HookOpts" ]; then
	grep ' need autoconf version 2.13 or' build/buildcheck.sh >/dev/null && export PHP_AUTOCONF='/usr/bin/autoconf2.13'
	mv configure configure0
	test "$Dbg" && cp -p configure0 $Logs
	./buildconf --force >$Logs/buildconf.out
	test "$Dbg" && cp -p configure $Logs
	mv $ConfigHelp $Logs/config0-help.out
	./configure --help >$ConfigHelp
    fi
fi
echo "Configuring php-$Ver$HookShow..."
test "$Dbg" && echo "ExtOpts=\"$ExtOpts\" HookOpts=\"$HookOpts\""

chkln /usr/lib libjpeg.a  x86_64-linux-gnu		# For PHP5
chkln /usr/lib libjpeg.so x86_64-linux-gnu
chkln /usr/lib libpng.a   x86_64-linux-gnu
chkln /usr/lib libpng.so  x86_64-linux-gnu
chkln /usr/lib libXpm.a   x86_64-linux-gnu
chkln /usr/include/freetype2/freetype freetype.h ..

chkln /usr/include curl x86_64-linux-gnu	# For OAuth

test -d /var/run/apache2 || mkdir /var/run/apache2	# For apache2 -V in configure
eval `grep '^export APACHE_' /etc/apache2/envvars`	# For apache2 -V in configure
SysconfDir='etc/php'
DataDir='usr/share/php'
PearDir="$DataDir"
ManDir='usr/share/man'
DocDir='usr/share/doc'
VarDir='var'
./configure \
	--prefix=/usr \
	--sysconfdir=/$SysconfDir \
	--with-config-file-path=/$SysconfDir \
	--with-config-file-scan-dir=/$SysconfDir/conf.d \
	--datadir=/$DataDir \
	--mandir=/$ManDir \
	--localstatedir=/$VarDir \
	--disable-debug \
	--disable-rpath \
	--disable-cgi \
	--with-pic \
	--with-pear=/$PearDir \
	--with-apxs2=/usr/bin/apxs \
	--with-freetype-dir=/usr \
	--with-jpeg-dir=/usr \
	--with-png-dir=/usr \
	--with-xpm-dir=/usr,/usr/X11R6 \
	--with-zlib-dir=/usr \
	--with-pdo-mysql=/usr \
	--with-mysqli=/usr/bin/mysql_config \
	--with-bz2 \
	--with-curl \
	--with-gd \
	--with-gettext \
	--with-iconv \
	--with-mhash \
	--with-pcre-regex \
	--with-openssl \
	--with-xsl \
	--with-zlib \
	$ExtOpts \
	$HookOpts \
	--enable-bcmath \
	--enable-ctype \
	--enable-dom \
	--enable-ftp \
	--enable-hash \
	--enable-json \
	--enable-libxml \
	--enable-mbstring \
	--enable-pdo \
	--enable-posix \
	--enable-session \
	--enable-simplexml \
	--enable-soap \
	--enable-sockets \
	--enable-sysvmsg \
	--enable-sysvsem \
	--enable-sysvshm \
	--enable-wddx \
	--enable-xml \
	--enable-xmlreader \
	--enable-xmlwriter \
	--enable-zip \
	--disable-debug \
>$Logs/config.out 2>&1
grep 'WARNING:' $Logs/config.out | egrep -v 'bison version|need re2c' || true	# true for set -e

# Add debian stuff to shutdown lintian's "hardening-no-relro" on jessie
# Taken from https://wiki.debian.org/Hardening so should work on all debian versions
sed -i '1i# Add debian hardening stuff\
export DEB_BUILD_MAINT_OPTIONS = hardening=+all\
DPKG_EXPORT_BUILDFLAGS = 1\
include /usr/share/dpkg/buildflags.mk\
' Makefile
grep '^EXTRA_LIBS = .* -lssl -lcrypto' Makefile >/dev/null || sed -i 's/-lxml2 -lxml2 -lxml2/-lssl -lcrypto/' Makefile

echo "Building php-$Ver..."
if ! make -k >$Logs/make.out 2>&1; then
    echo "\aBuilding php-$Ver FAILED:"
    grep "error:" $Logs/make.out
    exit 1
fi

set +e	# Continue on errors
if [ -f $Bld/.notest ]; then
    echo "Skiping php-$Ver tests."
else
    echo "Testing php-$Ver..."
    echo "s" | make test >$Logs/make-test.out 2>&1
    test -f php_test_results_*.txt && cp -p php_test_results_*.txt $Logs
fi

rm -f $Pkgs
Cli="`cat $Bld/pkgs/01-cli/name`-$Maj-$Min"
for dir in $Bld/pkgs/*
do
    Pkg=`basename $dir`
    Top=$dir/top
    Name="`cat $dir/name`-$Maj-$Min"

    if [ -f $dir/skip ]; then
	echo "Skipping package '$Pkg'"
	continue
    fi
    echo "Installing package '$Pkg'..."

    # doc directory
    sed -i "s/%YEAR%/`date '+%Y'`/" $Top/usr/share/doc/pkgname/copyright
    sed -i -e "s/%NAME%/$Name/g" -e "s/%VERSION%/$Ver/" -e "s/%DEBVER%/$DEBVER/" -e "s/%DATE%/`date -Rr $Bld/dist/.date`/" $Top/usr/share/doc/pkgname/changelog.Debian
    gzip -n9 $Top/usr/share/doc/pkgname/changelog*
    mv $Top/usr/share/doc/pkgname $Top/usr/share/doc/$Name

    # lintian overrides
    if [ -f $Top/usr/share/lintian/overrides/pkgname ]; then
	sed -i -e "s/%NAME%/$Name/g" -e "s/%MAJ%/$Maj/" $Top/usr/share/lintian/overrides/pkgname
	mv $Top/usr/share/lintian/overrides/pkgname $Top/usr/share/lintian/overrides/$Name
    fi

    # specific package install
    . $dir/install

    # DEBIAN directory
    sed -i -e "s/%VERSION%/$Ver-$BUILD_NUM/" -e "s/%NAME%/$Name/" -e "s/%DEPS%/$CLI_DEPS/" -e "s/%CLI%/$Cli/" $Top/DEBIAN/control

    # Gather extra license files
    find $Top -type f -iname license | while read f
    do
	lf=`echo $f | sed "s;^$Top/usr/share/doc/$Name/;;"`
	echo "Removing extra license file $lf."
	rm -v $f >>$Logs/rmed_$Pkg.out
    done

    echo "Assembling package '$Pkg'..."
    out=$(fakeroot dpkg-deb -Zgzip --build $Top $Bld/dist)
    deb=$(echo $out | sed "s/^.*building package ['\`][^']*' in ['\`]\([^']*\)'\.$/\1/")

    if [ -f "$deb" ]; then
	echo "Checking package '$Pkg' -> $deb..."
	lintian --allow-root $deb >$Logs/lintian_$Pkg.out
	echo "`basename $deb`" >>$Pkgs
    else
	test "$Dbg" && echo "out=\"$out\" deb=\"$deb\""
    fi
done

#make clean >$Logs/make-clean.out 2>&1
