FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV DEBVER=$DEBVER
ENV DEBNUM=$DEBNUM
ENV CLI_DEPS $CLI_DEPS
ENV BUILD_NUM=$BUILD_NUM
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN $ADDUSER
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\necho \"Use:\n    $BUILD_TOP/build\\nto start the build\"" >>/root/.bashrc

# Update/upgrade, install tools and build deps
$APT_SRC
RUN apt-get update && apt-get upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $BUILD_REQ

RUN mkdir -p $BUILD_TOP/dist $BUILD_TOP/files
COPY files/debinfo /usr/local/bin
$BLDCOPY

CMD [ "$BUILD_TOP/build" ]
