FROM debian:$DEBVER
MAINTAINER Epiconcept

ENV CLI_DEPS $CLI_DEPS
ENV BUILD_NUM=$BUILD_NUM
ENV DEBVER=$DEBVER
ENV USER=$USER
ENV LANG=C
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN echo "export TERM=xterm\nalias l='ls -Al'\necho \"Use:\n    $BUILD_TOP/build\\nto start the build\"" >>/root/.bashrc
RUN $ADDUSER

# Update/upgrade
RUN apt-get update
RUN apt-get upgrade -y

# Tools and build deps
RUN apt-get install -y --no-install-recommends $BUILD_REQ

RUN mkdir -p $BUILD_TOP/dist $BUILD_TOP/files
$BLDCOPY

CMD [ "$BUILD_TOP/build" ]
