#!/bin/sh
#
#	run - Run the main build/tests script in container, unless a .norun file exists
#
Dir=`dirname $0`
Ver="$1"

test -f $Dir/build && Bin="build" || Bin="tests"
Cmd="$Dir/$Bin $Ver"
test -f $Dir/.norun && echo "Only showing $Bin command as .norun is present: $Cmd" || $Cmd
