#!/bin/sh
#
#	start - Install multiple PHP versions in virtual hosts and start Apache
#
Prg=`basename $0`
Dir=`dirname $0`
Work="$Dir/work"
Logs="$Work/logs"
Pkgs="$Work/pkgs"
Base='epi-php'
Arch='amd64'
Domain="epiconcept.tld"
IpSite="http://ipaddr.free.fr"
DebNum=`expr \`cat /etc/debian_version\` : '\([0-9]*\)'`
test $$ -eq 1 && exec >$Logs/docker-run.out 2>&1

if [ ! -d $Pkgs ]; then
    echo "$Prg: directory $Pkgs is missing" >&2
    exit 1
fi
set -e
Dists="`ls $Pkgs | sed -nr "s/$Base-[5-9]\.[0-9]-(cli|fpm)_([5-9]\.[0-9]\.[0-9]+-[0-9]+)_$Arch.deb/\2/p" | sort -u`"
if [ -z "$Dists" ]; then
    echo "$Prg: no valid package name in $Pkgs" >&2
    exit 1
fi

sed -i '1iServername localhost' /etc/apache2/sites-available/000-default.conf
a2enmod proxy_fcgi >$Logs/a2.out

>$Logs/dpkg-i.out
for dist in $Dists
do
    eval `echo "$dist" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]+)-([0-9]+)$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
    if [ -s $Pkgs/$Base-$Maj.$Min-cli_${dist}_$Arch.deb -a -s $Pkgs/$Base-$Maj.$Min-fpm_${dist}_$Arch.deb ]; then
	dpkg -i $Pkgs/$Base-$Maj.$Min-cli_${dist}_$Arch.deb $Pkgs/$Base-$Maj.$Min-fpm_${dist}_$Arch.deb >>$Logs/dpkg-i.out
    else
	echo "$Prg: cannot find both cli and fpm packages for $dist"
	continue
    fi
    fpm=php$Maj.$Min-fpm
    www=$Work/www/php$Maj$Min
    site=php$Maj$Min.$Domain
    echo "<VirtualHost *:80>
    ServerName $site
    DocumentRoot $www
    <FilesMatch \".+\.ph(ar|p|tml)$\">
        SetHandler \"proxy:unix:/run/php/$fpm.sock|fcgi://localhost\"
    </FilesMatch>
    <Directory $www>
	AllowOverride all
	Require all granted
    </Directory>
</VirtualHost>" >/etc/apache2/sites-available/$site.conf
    a2ensite $site.conf >>$Logs/a2.out
    echo "Added site http://$site for host-dir debian/$DebNum/multi/www/php$Maj$Min"
    ok=y
done
IPAddr="`curl -sSL "$IpSite" 2>/dev/null | awk 'NR == 1 {print "IP=" $0} NR==2 { print "NS=" $0}'`"
if [ "$IPAddr" ]; then
    eval "$IPAddr"
    echo "Our IP address is $IP ($NS)"
fi
if [ "$ok" ]; then
    service apache2 start
    test $$ -eq 1 && exec waitpid
else
    echo "$Prg: no valid site to start" >&2
    exit 1
fi
