#!/bin/sh
#
#	tests - Test packages in $Tst/dist
#
Prg=`basename $0`
Tst=`dirname $0`
Ver="$1"
Pkgs="$Tst/dist/.pkgs-$Ver"
Logs="$Tst/dist/.logs-$Ver"

set -e	# Stop on errors
test -d $Logs || mkdir $Logs

if [ ! -f $Pkgs ]; then
    echo "$Prg: cannot find $Pkgs file" >&2
    exit 1
fi

while read pkg
do
    name=`echo $pkg | awk -F_ '{print $1}'`
    if dpkg -l $name >/dev/null 2>&1; then
	echo "Package $pkg is installed."
    else
	echo "Installing $pkg..."
	dpkg -i $Tst/dist/$pkg >>$Logs/dpkg-i.out 2>&1
    fi
done <$Pkgs
apt-get -yf install >$Logs/apt-get.out
echo "Testing PHP CLI..."
php /var/www/html/info.php >$Logs/info_01-cli.out
echo "Testing PHP apache module..."
curl -sSL http://localhost/info.php >$Logs/info_02-mod.out
