#!/bin/sh
#
#	tests - Test packages in $Tst/dist
#
Prg=`basename $0`
Tst=`dirname $0`
Ver="$1"
Logs="$Tst/dist/.logs"
Pkgs="$Tst/dist/.pkgs"

set -e	# Stop on errors

if [ ! -f $Pkgs ]; then
    echo "$Prg: cannot find $Pkgs file" >&2
    exit 1
fi
sed -i '1i\
Servername localhost' /etc/apache2/sites-available/000-default.conf

echo "Setting Apache 2 to prefork mode..."
a2dismod mpm_event >$Logs/a2mod.out 2>&1
a2enmod mpm_prefork >>$Logs/a2mod.out 2>&1

echo "Installing packages:"
test -d $Tst/pkgs && dpkg -i $Tst/pkgs/*.deb >$Logs/dpkg-i.out 2>&1

while read pkg
do
    if dpkg -l `echo $pkg | awk -F_ '{print $1}'` >/dev/null 2>&1; then
	echo "  . $pkg is already installed."
    else
	echo "  - $pkg"
	dpkg -i $Tst/dist/$pkg >>$Logs/dpkg-i.out 2>&1
    fi
done <$Pkgs

echo "Testing PHP CLI..."
php /var/www/html/info.php >$Logs/info_cli.out

echo "Testing PHP apache module..."
curl -sSL http://localhost/info.php >$Logs/info_mod.out
