#!/bin/sh

set -e

mkdir -p /var/lib/php/sessions
chmod 733 /var/lib/php/sessions
chmod o+t /var/lib/php/sessions

if [ -r /usr/share/apache2/apache2-maintscript-helper ]; then
    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke enmod php%MMJ%
fi

exit 0
