#!/bin/sh

set -e

ini=/etc/php%MMD%/php.ini
mod=mysql.so

grep "^extension *= *$mod *$" $ini >/dev/null || echo "extension = $mod" >>$ini
test -x /etc/init.d/apache2 -o -f /lib/systemd/system/apache2.service && service apache2 restart
exit 0
